[project]
name = "petremote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "catboost>=1.2.8",
    "flaml>=2.3.6",
    "imblearn>=0.0",
    "jupyter>=1.1.1",
    "koreanize-matplotlib>=0.1.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
    "optuna>=4.5.0",
    "pandas>=2.3.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
    "ultralytics>=8.3.180",
]
